### PR TITLE
28/fix edit item

### LINKED ISSUE #28: Edit Item optimistic mutation saves only part of the item

### PR DESCRIPTION
**Pull request by pyphilia**
close #28

### CODE REVIEW

File: src/mutations/item.ts [hunk 1]
```diff
@@ -113,25 +113,32 @@ export default (queryClient: QueryClient, queryConfig: QueryClientConfig) => {
...
+      await queryClient.cancelQueries(itemKey);
+
+      // build full item with new values
+      const prevItem = queryClient.getQueryData(itemKey) as Record<Item>;
+      const newFullItem = prevItem.merge(newItem);
+
       const previousItems = {
         parent: await mutateParentChildren({
-          childPath: newItem.path,
+          childPath: prevItem.get('path'),
```
Comment (juancarlosfarah) [inline src/mutations/item.ts:129]: Do we want to factor out `path` as some sort of `PATH_KEY` constant?

**Review by juancarlosfarah — APPROVED** [review]
Approving! Just a quick question in there.
