### PR TITLE
fix: trim items names on add and edit

### LINKED ISSUE #52: Trim item name on add and edit
The query client will need to trim the items names when created or edited.

This needs to be done when the request is sent to the server and when the value is stored in the cache.

Example :
`"My name "` does not pass the regex validation for item name.

### PR DESCRIPTION
**Pull request by Julien-Torrent**
This trim the item's name when created or edited.

closes #52 , grasp-compose#153

### CODE REVIEW

File: src/mutations/item.ts [hunk 1]
```diff
@@ -115,6 +115,13 @@ export default (queryClient: QueryClient, queryConfig: QueryClientConfig) => {
     mutationFn: (item) => Api.editItem(item.id, item, queryConfig),
     // newItem contains only changed values
     onMutate: async (newItem: Partial<Item>) => {
+      newItem = {
+        ...newItem,
+        name: newItem.name?.trim()
+      };
+
+      console.log(newItem);
```
Comment (pyphilia) [inline src/mutations/item.ts:123]: Remove this console. Maybe let's not mutate the argument directly, create a new variable.

**Review by pyphilia — CHANGES_REQUESTED** [review]
Good! I left a minor comment, and you can merge! 🔥
