### PR TITLE
fix(type): of useTags hook

### LINKED ISSUE #253: Fix `useTag` return type
Current return type of `useTags` is 
`ItemtagRecord` when it should be `TagRecord`.

### PR DESCRIPTION
**Pull request by spaenleh**
This PR fixes the return type of the `useTags` hook.

closes #253

### CODE REVIEW

File: src/hooks/itemTag.ts [hunk 1]
```diff
@@ -2,7 +2,7 @@ import { List } from 'immutable';
 import { QueryClient, useQuery } from 'react-query';
 
 import { UUID, convertJs, isError } from '@graasp/sdk';
-import { ItemTagRecord } from '@graasp/sdk/frontend';
+import { ItemTagRecord, TagRecord } from '@graasp/sdk/frontend';
```
Comment (dialexo) [inline src/hooks/itemTag.ts:5]: Is there are reason why both are still imported?

**Review by dialexo — APPROVED** [review]
LGTM :bubble_tea: see comment
