### PR TITLE
157/fix favorite

### LINKED ISSUE #157: Favorite item add repeated id

### PR DESCRIPTION
**Pull request by louisewang1**
close #157 
This PR fix the problem of adding two copies of id to favorite items. However, if currently some member already have repeated ids, we need to manually unfavorite and re-favorite to fix the error @pyphilia

### CODE REVIEW

File: src/mutations/member.ts [hunk 1]
```diff
@@ -113,11 +113,8 @@ export default (queryClient: QueryClient, queryConfig: QueryClientConfig) => {
 
   // mutation to update favorite items of given member
   queryClient.setMutationDefaults(MUTATION_KEYS.ADD_FAVORITE_ITEM, {
-    mutationFn: (payload) => {
-      const { memberId, itemId, extra } = payload;
-      extra.favoriteItems = extra.favoriteItems
-        ? extra.favoriteItems.concat([itemId])
-        : [itemId];
+    mutationFn: async (payload) => {
+      const { memberId, extra } = payload;
```
Comment (pyphilia) [inline src/mutations/member.ts:117]: What's the logic here? Has `extra` already been changed at this point? It doesn't seem so since you're changing it in `onMutate`.. I might be wrong but you never update the database actually.

**Review by pyphilia — CHANGES_REQUESTED** [review]
Thanks for the change 🦋  but I have one question.

**Review by pyphilia — APPROVED** [review]
It looks good to me, I hope javascript is clearer for you now 👀
