### PR TITLE
fix: use ThumbnailSize from sdk

### LINKED ISSUE #251: Use ThumbnailSize from sdk

### PR DESCRIPTION
**Pull request by spaenleh**
This PR uses ThumbnailSizes defined in sdk instead of own constant

closes #251

### CODE REVIEW

File: src/config/constants.ts [hunk 1]
```diff
@@ -1,5 +1,7 @@
 import { StatusCodes } from 'http-status-codes';
 
+import { ThumbnailSize } from '@graasp/sdk/frontend';
```
Comment (pyphilia) [inline src/config/constants.ts:3]: Actually I will need this in the front as well  👀  does that mean it should be moved out of frontend?

**Review by pyphilia — APPROVED** [review]
Niiice 🌴

File: package.json [hunk 2]
```diff
@@ -103,7 +103,7 @@
     "release": "standard-version",
     "lint": "eslint .",
     "post-commit": "git status",
-    "type-check": "tsc --noEmit",
+    "type-check": "tsc --noEmit --project tsconfig.test.json",
```
Comment (dialexo) [inline package.json:106]: Is this intended?

File: src/config/constants.ts (hunk 1 above)
Comment (dialexo) [reply src/config/constants.ts:3]: Do you mean in the back-end as well? 😅

File: tsconfig.test.json [hunk 3]
```diff
@@ -26,6 +26,6 @@
     "isolatedModules": true,
     "noEmit": true
   },
-  "include": ["test"],
+  "include": ["test", "src"],
```
Comment (dialexo) [inline tsconfig.test.json:29]: Isn't this tsconfig supposed to only handle compilation in test mode?

**Review by dialexo — COMMENTED** [review]
LGTM but I have a question regarding tsconfig 🤔

File: package.json (hunk 2 above)
Comment (spaenleh) [reply package.json:106]: Yes, I want to check all files for TS errors, test files as well. Otherwise type issues only arrive when actually **running** the tests which is a bummer.

File: tsconfig.test.json (hunk 3 above)
Comment (spaenleh) [reply tsconfig.test.json:29]: I don't think we compile the tests... and this was the only way I found to have ts check all files when developing.

File: package.json (hunk 2 above)
Comment (spaenleh) [reply package.json:106]: The issue is that I want to be able to run my `yarn check` or `yarn type-check` command locally and be sure that all my code is correct. I don't want to have my tests catch a type error I could have fixed before sending to the CI or running the full checks on git hooks (which will fail my commit which i find very annoying ...)

Comment (dialexo) [reply package.json:106]: I see what you mean. I often consider test to be its own environment anyway (since it will be compiled and ran through e.g. `ts-node`). But either is fine by me 👍
