### PR TITLE
fix: complete action type

### LINKED ISSUE #232: Complete action types

### PR DESCRIPTION
**Pull request by pyphilia**
close #232

### CODE REVIEW

File: src/types.ts [hunk 1]
```diff
@@ -208,9 +208,22 @@ export interface Action {
...
 
 export type ActionRecord = RecordOf<Action>;
+export type ActionMetadata = {
+  numActionsRetrieved: number;
+  requestedSampleSize: number;
+};
+export type ActionMetadataRecord = RecordOf<{
+  numActionsRetrieved: number;
+  requestedSampleSize: number;
+}>;
```
Comment (spaenleh) [inline src/types.ts:218]:
```suggestion
export type ActionMetadataRecord = RecordOf<ActionMetadata>;
```

**Review by spaenleh — APPROVED** [review]
LGTM ! Just a simplificaiton of the record type. 🦤
