### PR TITLE
fix: remove cookie when logout is confirmed, prevents logout loop

### LINKED ISSUE #40: Remove cookie in browser when signing out
ref https://github.com/graasp/graasp-feedback/issues/10

### PR DESCRIPTION
**Pull request by Julien-Torrent**
This only update the user state when the backend confirms the logout

close #40

### CODE REVIEW

**Review by juancarlosfarah — APPROVED** [review]
I'm approving this as it makes total sense, but maybe @pyphilia wants to have a look Monday morning?

**Review by pyphilia — APPROVED** [review]

File: src/mutations/member.ts [hunk 1]
```diff
@@ -19,18 +19,19 @@ export default (queryClient: QueryClient, queryConfig: QueryClientConfig) => {
       // Snapshot the previous value
       const previousMember = queryClient.getQueryData(CURRENT_MEMBER_KEY);
```
Comment (pyphilia) [inline src/mutations/member.ts:20]: Thanks for your changes! Perhaps remove the logic for `previousMember` as we are not using it anymore?

**Review by pyphilia — CHANGES_REQUESTED** [review]

**Review by pyphilia — CHANGES_REQUESTED** [review]
Thanks for the changes. You'll need to remove line 29 too.
